#!/usr/bin/env python3
"""MiniCPM-o 4.5 Demo Page 构建脚本

从 edit_tool 的 data.json 读取配置，
从 edit_tool/resources/ 复制音频资源，
生成 data.js 到 minicpm-o-4_5/。

资源来源：develop/edit_tool/resources/audio/
数据来源：develop/edit_tool/config/data.json（优先）
         develop/minicpm-o-4_5/config/cases.json（回退）

Usage:
    cd /path/to/openbmb.github.io
    python develop/minicpm-o-4_5/build.py
"""

import json
import shutil
from pathlib import Path
from typing import Union


# === 路径配置 ===
SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent.parent
CONFIG_PATH = SCRIPT_DIR / "config" / "cases.json"
EDIT_TOOL_DIR = SCRIPT_DIR.parent / "edit_tool"
EDIT_TOOL_CONFIG = EDIT_TOOL_DIR / "config" / "data.json"
RESOURCES_DIR = EDIT_TOOL_DIR / "resources"
OUTPUT_DIR = REPO_ROOT / "minicpm-o-4_5"


def get_text(obj: Union[str, dict], lang: str = "zh") -> str:
    """从多语言对象中获取指定语言的文本"""
    if isinstance(obj, dict):
        return obj.get(lang, obj.get("zh", ""))
    return obj


def load_config() -> dict:
    """加载配置文件
    
    优先级：
    1. edit_tool/config/data.json（编辑器保存的，包含完整数据）
    2. minicpm-o-4_5/config/cases.json（原始模板）
    """
    if EDIT_TOOL_CONFIG.exists():
        print(f"[INFO] 从 edit_tool 配置加载: {EDIT_TOOL_CONFIG}")
        with open(EDIT_TOOL_CONFIG, "r", encoding="utf-8") as f:
            return json.load(f)
    
    print(f"[INFO] 从默认配置加载: {CONFIG_PATH}")
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def copy_resources(output_audio_dir: Path) -> dict:
    """从 edit_tool/resources/audio/ 复制音频到输出目录
    
    Args:
        output_audio_dir: 输出音频目录 (minicpm-o-4_5/audio/)
    
    Returns:
        统计信息 {"files": int, "cases": int}
    """
    source_audio_dir = RESOURCES_DIR / "audio"
    stats = {"files": 0, "cases": 0}
    
    if not source_audio_dir.exists():
        print(f"[WARN] 资源目录不存在: {source_audio_dir}")
        return stats
    
    for case_dir in sorted(source_audio_dir.iterdir()):
        if not case_dir.is_dir():
            continue
        
        target_case_dir = output_audio_dir / case_dir.name
        target_case_dir.mkdir(parents=True, exist_ok=True)
        
        file_count = 0
        for audio_file in sorted(case_dir.iterdir()):
            if audio_file.is_file() and audio_file.suffix in ('.mp3', '.wav', '.ogg', '.m4a'):
                shutil.copy2(audio_file, target_case_dir / audio_file.name)
                file_count += 1
        
        if file_count > 0:
            stats["cases"] += 1
            stats["files"] += file_count
            print(f"  复制 {case_dir.name}: {file_count} 个音频文件")
    
    return stats


def build_data(config: dict) -> dict:
    """构建 data.js 数据
    
    直接使用 config 中的数据结构，不再从 collected sessions 读取。
    音频文件路径已在编辑器中维护。
    
    Args:
        config: 编辑器保存的配置数据
    
    Returns:
        最终的数据结构
    """
    output_data = {
        "meta": config.get("meta", {}),
        "abilities": []
    }
    
    for ability in config.get("abilities", []):
        output_ability = {
            "id": ability["id"],
            "name": ability.get("name", ""),
            "description": ability.get("description", ""),
            "sub_abilities": []
        }
        
        for sub_ability in ability.get("sub_abilities", []):
            output_sub = {
                "id": sub_ability["id"],
                "name": sub_ability.get("name", ""),
                "description": sub_ability.get("description", ""),
                "cases": []
            }
            
            for case in sub_ability.get("cases", []):
                output_case = {
                    "id": case["id"],
                    "summary": case.get("summary", ""),
                    "system": case.get("system", {}),
                    "turns": case.get("turns", [])
                }
                output_sub["cases"].append(output_case)
            
            output_ability["sub_abilities"].append(output_sub)
        
        output_data["abilities"].append(output_ability)
    
    return output_data


def write_data_js(data: dict, output_dir: Path, filename: str = "data.js"):
    """将数据写入 data.js"""
    data_js_path = output_dir / filename
    
    # 格式化 JSON，便于阅读
    json_str = json.dumps(data, ensure_ascii=False, indent=2)
    
    content = f"// Auto-generated by build.py - DO NOT EDIT\nconst DEMO_DATA = {json_str};\n"
    
    data_js_path.write_text(content, encoding="utf-8")
    print(f"写入 {data_js_path}")


def main():
    print("=" * 60)
    print("MiniCPM-o 4.5 Demo Page Builder")
    print("=" * 60)
    print(f"资源来源: {RESOURCES_DIR}")
    print(f"输出目录: {OUTPUT_DIR}")
    print()
    
    # 清理输出目录中的音频（保留其他文件）
    output_audio_dir = OUTPUT_DIR / "audio"
    if output_audio_dir.exists():
        print(f"清理音频目录: {output_audio_dir}")
        shutil.rmtree(output_audio_dir)
    output_audio_dir.mkdir(parents=True, exist_ok=True)
    
    # 复制音频资源
    print("\n" + "=" * 40)
    print("复制音频资源")
    print("=" * 40)
    audio_stats = copy_resources(output_audio_dir)
    print(f"  共复制 {audio_stats['cases']} 个 case, {audio_stats['files']} 个文件")
    
    # 加载配置
    config = load_config()
    
    # 构建数据
    print("\n" + "=" * 40)
    print("构建数据")
    print("=" * 40)
    output_data = build_data(config)
    
    # 写入 data.js
    write_data_js(output_data, OUTPUT_DIR, "data.js")
    
    # 统计
    total_cases = sum(
        len(sub["cases"])
        for ability in output_data["abilities"]
        for sub in ability["sub_abilities"]
    )
    
    print("\n" + "=" * 60)
    print(f"构建完成！")
    print(f"  Cases: {total_cases}")
    print(f"  音频: {audio_stats['files']} 个文件")
    print(f"  输出: {OUTPUT_DIR / 'data.js'}")
    print("=" * 60)
    
    return 0


if __name__ == "__main__":
    exit(main())
